### ISSUE TITLE
Implement Swamp Groundtype

### ISSUE THREAD

**Issue by VagrantBlackbird** [Siriah/codegarden#11]
The swamp is a groundtype that slows down creatures walking into it, but otherwise acts as ground. 

- Gnomes require two turns instead of one to walk through swamp. This does not mean two actions are required, but rather that one action takes two turns. 

Example:
Say you have tiles 1,2,3,4, with a Gnome starting on space 1 and wanting to go to space 4
In Case A, there is no swamp
In Case B, tile 2 is a swamp tile
In Case C, tile 2 and 3 are a swamp tile

For case A, the movement will be:
Forward (tile 2) - Forward (tile 3) - Forward (tile 4)
For a total of 3 turns until the 3 actions are done

For case B, the movement will be 
Forward (tile 2; moving into swamp) - Nothing (tile 2; getting out of swamp) - Forward (tile 3) - Forward (tile 4)
For a total of 4 turns until the 3 actions are done

For case C, the movement will be 
Forward (tile 2; moving into swamp) - Nothing (tile 2; getting out of swamp) - Forward (tile 3; more swamp) - Nothing (tile 3; getting out of swamp) - Forward (tile 4)
For a total of 5 turns until the 3 actions are done

This changes timing of Gnomes to make puzzles a bit more complicated.

- Gnomes that are floating will negate the effects of swamp as long as they are floating 
- Traversing a crocodile over a swamp negates the effects of the swamp

**Comment by Siriah** [comment]
Also, gnomes who stand still on a swamp tile should drown.

Mostly implemented in 42bd71b80948370aef961c06311dc745827f6fb7 but the graphics are still missing.

**Comment by Siriah** [comment]
Graphics added in 5a9e840280c980fdc562e8b8071d6682c039ea90
