### ISSUE TITLE
Stacking commands can overflow the screen height

### ISSUE THREAD

**Issue by jorisslob** [Siriah/codegarden#5]
When inputting commands into your program in the box below, you can keep on adding commands until they overflow the screen height. This means that I cannot see the entire program. Maybe there should be a maximum to the length of the program box, and/or it the blocks in it should resize to allow more commands.

My screen size was 1280x800. If there are requirements on the screen size, this should also be documented.

**Comment by Siriah** [comment]
Programs are now limited in size (configured per gnome house depending on what's needed to finish a level). The size limits are currently strict enough that even at resolutions as small as 1024 x 768 it will all fit. We might need to revisit this issue if we decide to allow programs of unlimited size, but that's unlikely as we're planning to introduce libraries in the fourth level.
